//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Strahovanu9.Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treaty
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public Nullable<int> Agent { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal AmountInsurance { get; set; }
        public int IdInsurancePayments { get; set; }
        public Nullable<int> IdKindSport { get; set; }
        public int Period { get; set; }
    
        public virtual InsurancePayments InsurancePayments { get; set; }
        public virtual KindSport KindSport { get; set; }
        public virtual Peruod Peruod { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
